### ISSUE TITLE
Configuration ? 

### ISSUE THREAD

**Issue by meme0623** [djphil/osintercom#2]
Bonjour Dj phil ,c'est vlad ,il y a t'il une configuration particulière qui m’aurais échappée ? 
lorsque j'ecris un text il ne s'affiche pas :  http://virtualdream-grid.com/vdintercom/
Le script inworld lorsque j’écris ça me met configuration et idem ,rien de plus ensuite . 

Amitiés Vlad

**Comment by djphil** [comment]
Bonjour Vlad,
merci d'avoir signalé ce problème de compatibilité avec PHP 7.x
Il est résolu dans le commit 553d3f00b1e5d95cd875333fceb422f03f9778ce 
.

**Comment by meme0623** [comment]
Merci Djphil ,du coup outworld cela fonctionne maintenant ,mais car il y a un mais ,cela ne fonctionne pas inworld ,je voit dans le script que ca doit pointer vers un chat.php et ce fichier je ne l'ai pas

**Comment by djphil** [comment]
Fixé dans 4c9fdd3cb19def30dcb22f923ae41c464e0c9424, merci!

**Comment by meme0623** [comment]
Effectivement j'avais trouvé cela ,j'ai reussi un test concluant ,puis voulant reessayer maintenant j'ai ca dans le tchat local : [10:59]  vdintercom hud v0.1: Initialisation ...
[10:59]  vdintercom hud v0.1: Please wait vladimir Djannovic ...
[10:59]  vdintercom hud v0.1: Click one more time vladimir Djannovic ...
[10:59]  vdintercom hud v0.1: Intercom @ http://tinyurl.com/y6btbyde

et la prim reste désespérément couleur prim , le test réussi j'ai du avoir de la chance ,mais maintenant impossible .

**Comment by meme0623** [comment]
je clos ,merci djphil
